gosqasorg/asset-provenance-tracking

- views/device.liquid
> remove device id from /device page

- public/ProvenanceForm.js
- views/device.liquid
- views/devices.liquid
- views/provenance.liquid
> Visual styling of Provenance records page

- package-lock.json
- server.ts
- views/devices.liquid
- views/index.liquid
> /info redirect + project description on home page

- views/device.liquid
@devhawk This is a simple fix done with Judith Weng to get her started.
> removing Device ID as per issue #41

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
Accidently merged issue templates & copywrite updates into the same branch.
Happy to separate and into two different pull requests if needed otherwise don't hesitate to merge if not
Would resolve #61 if merged
> fix: Makes minor copywrite updates to readme & adds issue templates

- README.md
> fix: Makes commands one click copyable & easier to follow

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- package-lock.json
- package.json
- packages/backend/.funcignore
- packages/backend/.gitignore
- packages/backend/.vscode/extensions.json
- packages/backend/README.md
- packages/backend/host.json
- packages/backend/local.settings.json
- packages/backend/package.json
- packages/backend/src/functions/httpTrigger.ts
- packages/backend/tsconfig.json
Adds the azure function backend that I've been working on in a different repo. 
I've written up some docs for how to invoke the endpoints: [Calling the GOSQAS backend](https://github.com/gosqasorg/asset-provenance-tracking/wiki/Calling-the-GOSQAS-backend)
fixes #56
fixes #55 (this PR uses SHA 256 instead of FNV for hashing)
> Add Azure Function Backend Project

- packages/legacy/views/layout.liquid
> Removed hamburger menu from legacy frontend

- README.md
> feat: Adds license section to repo

- packages/frontend/components/Provenance/TagInput.vue
This is an addition of Nora's code.
> Forbidden Tags

- packages/frontend/components/CreateContainer.vue
- packages/frontend/components/CreateDevice.vue
- packages/frontend/components/KeyList.vue
- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/pages/provenance/[deviceKey].vue
> Container system - adding children after creation

- packages/frontend/components/CreateContainer.vue
- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/pages/provenance/[deviceKey].vue
fixes #98 
Adding input fields for users to customize children names if they want. Children devices are then named after what the user entered.
> create form to customize children names

- packages/frontend/components/Provenance/NotificationSignUpModal.vue
- packages/frontend/package.json
- packages/frontend/pages/provenance/[deviceKey].vue
This is currently commented out so it wont show in the UI (because the notification system is not fully functional, I don't want the user to see this yet). This would be a good next step for the design team to tackle. Maybe make a modal etc. 
This is the basic functionality needed.
> Notification Sign up Form

- packages/frontend/assets/styles/main.scss
- packages/frontend/layouts/default.vue
Fixed padding and sizing of navbar elements to match Figma design. (Also fixed universal color to match Figma.)
For a future PR: Still need to fix hamburger menu icon and button fonts/colors.
> Nav-bar Formating Update

- packages/frontend/assets/styles/main.scss
- packages/frontend/pages/device/[deviceKey].vue
Fixes #193 
Referenced the Figma for style changes.
> Fixed Device Page Text Styling 

- packages/frontend/components/Forms/CreateContainer.vue
- packages/frontend/components/Provenance/CreateRecord.vue
Allow every other file type to containers and records
> Issue with Attaching Non-PNG Files to Containers and Records

- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/components/Provenance/Feed.vue
This PR solves #248. The 'Create New Record' form has been styled to match the latest Figma design.
As stated in PR #253, the button components have a font size that cannot be changed. The button to submit a record does not have the correct font size and needs to be changed.
> 'Create New Record' form

- packages/frontend/layouts/default.vue
Add a footer at the bottom of the website
> Coco adds a footer

- packages/frontend/assets/styles/main.scss
- packages/frontend/layouts/default.vue
- packages/frontend/pages/index.vue
Update the styling to make the footer stick to the bottom of the page if there is not enough content.
Issue: https://github.com/gosqasorg/asset-provenance-tracking/issues/285
> Make footer sticky.

- packages/frontend/components/Provenance/Feed.vue
> Fixed thumbnail issue.

- packages/frontend/components/Forms/CreateContainer.vue
- packages/frontend/components/Forms/CreateDevice.vue
- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/components/Provenance/Feed.vue
Small PR to remove commented out code, unused variables and debug console.log statements.
> Remove unused code.

- packages/frontend/components/ButtonComponent.vue
- packages/frontend/components/Forms/CreateContainer.vue
- packages/frontend/components/Forms/CreateDevice.vue
I implemented custom text sizes by making a custom css class in ButtonComponent that can be set to either true or false when creating a button (I give an example of this in the comments at the bottom of ButtonComponent). To make a new custom button size you would have to make a new css class, it’s a little messy but it works.
> Added custom font sizes to ButtonComponent.vue

- packages/frontend/components/Buttons/LargeToggle.vue
- packages/frontend/components/Forms/CreateContainer.vue
- packages/frontend/components/Forms/CreateDevice.vue
- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/components/Provenance/Feed.vue
- packages/frontend/components/TrackAsset.vue
- packages/frontend/layouts/default.vue
- packages/frontend/layouts/learn_more.vue
- packages/frontend/pages/home.vue
- packages/frontend/pages/index.vue
- packages/frontend/pages/provenance/[deviceKey].vue
I implemented all the changes stated in the issue, the only thing I wasn't able to do was replaced the Technical Documents link with the Terms and Condition link, as I wasn't sure what the link to the Terms and Conditions page was.
> Changed language according to new FIGMA design

- packages/frontend/pages/device/[deviceKey].vue
- packages/frontend/pages/provenance/[deviceKey].vue
- packages/frontend/utils/descendantList.ts
Fixed the child keys appearing at the bottom of reporting keys and child keys' pages of containers.
> Declutter container system

- packages/frontend/nuxt.config.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
closes #333
Update frontend pacakges to resolve vulnerabilities.
> Update frontend packages.

- packages/frontend/components/Provenance/CreateRecord.vue
I added the spacing between the footer and the form when you scroll down, trying to match the amount of spacing to the FIGMA design.
> Fixed footer spacing issue

- packages/backend/package-lock.json
- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/components/Provenance/PriorityNotices.vue
- packages/frontend/components/csvFile.vue
- packages/frontend/pages/provenance/[deviceKey].vue
- packages/frontend/services/azureFuncs.ts
- packages/frontend/utils/descendantList.ts
Previous renaming of device to record broke the add record to feed functionality.
> Fix broken props.

- packages/backend/host.json
Set log levels for Function app to Information to get them to show context.log statements.
> Update logging for backend.

- packages/frontend/components/Provenance/CreateRecord.vue
Remove notify all checkbox on record form
> Remove notify all checkbox on record form

- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/pages/provenance/[deviceKey].vue
- packages/frontend/utils/descendantList.spec.ts
- packages/frontend/utils/descendantList.ts
closes #317 plus fixes a couple minor bugs
> 317 remove container field

- packages/frontend/components/Provenance/CreateRecord.vue
- packages/frontend/components/Provenance/Feed.vue
- packages/frontend/pages/device/[deviceKey].vue
- packages/frontend/pages/provenance/[deviceKey].vue
- packages/frontend/services/azureFuncs.ts
- packages/frontend/utils/clickableLink.ts
- packages/frontend/utils/descendantList.ts
- packages/frontend/utils/keyFuncs.spec.ts
- packages/frontend/utils/keyFuncs.ts
- packages/frontend/utils/tags.ts
A few changes to address some bugs and to improve the user experience (based on user feedback).
- Added helper function to validate key.
- Added helper functions to determine if a record is a group.
- Added helper function to search over the list of immutable records for changes, eg. adding child keys or adding a record to a group is appended, so it may not be in the first record. Now can search for 'features' in the record and then use those in the app.
- Improved load times by reducing number of HTTP calls; actual reduction in calls and also increased client-side error checking to reduce superfluous calls.
- Improved user experience by only updating the feed component instead of reloading the entire page.
- Added enumerated tags.
- Added very simple loading text.
> UX improvements

- packages/frontend/pages/index.vue
Fixed typo in the word "transparency" on the homepage.
> Fixed Type on Homepage

- packages/frontend/pages/index.vue
I added the new line to the hero section, as well as adjusting the formatting on mobile so that the text didn't go outside of its box.
> Added new line to Hero Section

- packages/frontend/components/Forms/CreateContainer.vue
- packages/frontend/components/Forms/CreateDevice.vue
- packages/frontend/components/GenerateQRCode.vue
- packages/frontend/components/KeyList.vue
- packages/frontend/components/TrackAsset.vue
- packages/frontend/components/csvFile.vue
- packages/frontend/middleware/redirect.global.ts
- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
- Rename all links from provenance to history and device to record
- Add redirects for backwards compatability
> Redirect provenance/ to history/ and device/ to record/

- packages/frontend/error.vue
Created the custom 404 page that now shows up instead of the default one.
> Created Custom 404 Page

- .gitignore
- packages/frontend/pages/record/[deviceKey].vue
- Need to initialize route object.
> Fix broken redirect.

- packages/frontend/pages/donate.vue
I created the donation page, there were only 2 things that I wasn't able to add.
- There was a link in the design to our current open positions, but no link was provided on the FIGMA
- The third box had no text (just labeled 'another thing')
I left TODO comments on those parts of the code, and can implement them once the design is finalized.
> Created Donation Page

- packages/frontend/pages/record/[deviceKey].vue
Single work change, please approve and merge ASAP --- this is needed for the video.
> removing Provenance word and changing to history, fixes #406

- packages/frontend/pages/donate.vue
Donation page should be all set, however we still don't have anywhere on the site that links to this page.
> Updated donation page to match FIGMA

- packages/frontend/components/Provenance/Feed.vue
- packages/frontend/nuxt.config.ts
- packages/frontend/package-lock.json
- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
- packages/frontend/staticwebapp.config.json
- packages/frontend/utils/event-bus.ts
Fix bugs in staging - check for null, fix modal not rendering correctly, removed unused code.
Also closes #393
> Fix staging

- packages/frontend/pages/data-privacy.vue
Updated the Data & Privacy text language. 
Issue #408  for this PR.
> Updated the Data & Privacy language text

- packages/frontend/components/TrackAsset.vue
- packages/frontend/pages/index.vue
PR for issue #396  
Changes in index.vue
- Swapped the order of "View Record" and "Create Record" buttons 
- Changed "Create Record" button background color from light blue (#CCECFD) to purple (#4E3681)
Changes in TrackAsset.vue
- Modified the "View Record" button within the TrackAsset component
- Changed button colors to match the main page's "View Record" button styling
Before changes
After changes
> Update button colors and swap positions on home page 

- packages/frontend/layouts/default.vue
> Donate page added to main menu 

- packages/backend/src/functions/httpTrigger.ts
> Fixes #423.

- packages/frontend/components/Provenance/Feed.vue
- packages/frontend/nuxt.config.ts
- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
The entries are numbered, but there needs to be some clarification on how they should be numbered (i.e., backwards or like what is below?)
> Numbered entries

- packages/frontend/components/TrackAsset.vue
- packages/frontend/pages/index.vue
Now shows Track Asset field on the homepage (index.vue file) using Vue components, rather than accessing the DOM. Also changed the 'View Record' and 'Create Record' buttons' colors to match the FIGMA.
> Replaced DOM Access with Vue Element

- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
> Fixed Dark Mode text and other changes

- packages/frontend/components/csvFile.vue
- Issue #461 
- added headers and listed the child name, parent record key, reporting key, & child key URL
> Children Keys CSV Update

- packages/frontend/pages/dmdm.vue
Made the requested changes to the DMDM page, adding the new text and fixing the bullet point section.
> Updated DMDM Page

- packages/frontend/components/Provenance/ShareDropdown.vue
- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
- packages/frontend/utils/keyFuncs.ts
Created a component for the share dropdown (which appears on both the record and history pages). When looking over the code I didn't see any more duplicated code, at least not anything that was obvious.
> Created Share Dropdown Component

- packages/frontend/components/Provenance/ShareDropdown.vue
- packages/frontend/pages/history/[deviceKey].vue
- packages/frontend/pages/record/[deviceKey].vue
- packages/frontend/utils/keyFuncs.ts
Now when creating 500 children keys all of them are created successfully. The issue was that sometimes when creating a new child key the new key would only be 21 characters long (instead of the required 22 characters), which would cause the key to fail. Now the code checks the length of the child key during creation and will retry if it is not 22 characters long.
> Added Error Handling for Creating Children Keys

- packages/frontend/pages/about.vue
- packages/frontend/pages/dmdm.vue
- packages/frontend/pages/donate.vue
- packages/frontend/pages/how-it-works.vue
- packages/frontend/pages/index.vue
For #499 
Added "Video production by Prodigium Pictures" below video on the site in 5 pages:
homepage
about us
how it works
donation page
dmdm page
> Text under video

- packages/frontend/pages/about.vue
> Team section added to About Us page

- packages/frontend/pages/about.vue
Changed the wording as requested.
parent issue #592
> changed the wording and completed

- .husky/pre-commit
- .prettierignore
- .prettierrc
- package-lock.json
- package.json
Issue #268 and adding backend files to be ignored #577
> Format styling on commit
