gosqasorg/asset-provenance-tracking

package-lock.json, server.ts
This adds two entry points:
1. An entry point to allow any number of keys (records) to be created in a single operation.
2. An entry point which does not modify the database, but allows a download of the QR code .png for a device key (presumably, looping over the N keys created with entry point 1.
=> Rob batch download

packages/backend/src/functions/httpTrigger.ts, packages/backend/test/test.ts
* Update getProvenance to include deviceID as sibling of timestamp instead of part of record object
* ensure gosqas container exists in getStatistics
* add getStatistics option to test script
fix #120
=> Assorted Backend

packages/frontend/components/Provenance/CreateRecord.vue, packages/frontend/pages/device/[deviceKey].vue, packages/frontend/pages/provenance/[deviceKey].vue
fixes issue #151 
This prevents a device from becoming simultaneously both a parent and a descendant of another device. 
When the user adds a device that creates such relationship, an error is displayed.
=> preventing circular relationships

packages/frontend/utils/colorTag.ts
This fixes issue #186 
The issue seemed to be that the tag "at" was detected as a designed tag but since it is actually NOT a designed tag, it returns an undefined value. I changed the syntax of how we defined `designedTags` and it fixed the issue. Image below shows old code as commented.
Image below shows tag "at" working.
=> Fixing color tag bug

packages/frontend/components/csvFile.vue
Fixes issue #210. Current csv file separates each key in a new line rather than a coma. In addition, each key has been converted to a link to its provenance. This is the current format: https://gosqas.org/provenance/{key}.
=> Changing csv format

packages/frontend/layouts/default.vue
Fixes for issue #170. Made the icon match the FIGMA and fixed the issue where the hamburger bar would move to a new line when the screen got too small. Screen sizes smaller than 187px will go back to two lines, but to my knowledge no screen sizes are that small so it shouldn't be an issue.
=> Fix hamburger bar styling

README.md, packages/frontend/README.md, packages/frontend/assets/styles/main.scss, packages/frontend/components/GenerateQRCode.vue, packages/frontend/nuxt.config.ts, packages/frontend/pages/index.vue
=> Adding Copyrights for branding

package-lock.json, packages/frontend/pages/provenance/[deviceKey].vue
I fixed the spacing for the Jump to Section menu (on the Asset History Records page) and got Nina's approval for the new spacing.
=> Fixed Spacing for Jump to Section Menu

packages/frontend/assets/styles/main.scss, packages/frontend/components/TrackAsset.vue, packages/frontend/layouts/learn_more.vue, packages/frontend/pages/about.vue, packages/frontend/pages/data_privacy.vue, packages/frontend/pages/home.vue
This is a very large PR that essentially styles the 'Home', 'About Us', 'How it Works' and 'Data & Privacy' pages. The specifics are listed below.
1. Fixes #244 : The previous PRs #234 and #226 created the 'How it Works' and 'Home' page. However, these did not contain buttons. In this PR, the buttons are added thanks to Ally's button component #243.
2. Fixes #201 : An 'About' page already existed from one of Nora's old PR. This page had most of the contents but did not have the latest design. In this PR, the 'About' page follows the latest Figma design.
3. Fixes #203 : A 'Data & Privacy' page was made in this PR following the latest Figma design.
Things missing or to fix:
1. The 'Home' page is still not our official home page, but I think once this PR is approved, then we can immediately …
=> Adding buttons to pages

packages/frontend/components/Provenance/Feed.vue
This PR fixes #255 and #254.
A single long word is now contained within the gray box and does not 'escape' out of it.
In addition, when a user uploads a file(s), the feed will show a preview and a link that says 'Download Image'. This link was changed to say 'Download File' so that users do not get confused when a PDF or any other non-image file is uploaded. The preview now is only available if users upload an image; they are unable to preview a non-image file. See image below.
=> 'Download Image' and Long Words Issue in Provenance Feed

packages/backend/package-lock.json, packages/backend/package.json, packages/backend/src/functions/httpTrigger.ts, packages/backend/tsconfig.json
* add `convertLegacyProvenance` function that converts legacy prov records/attachments under the `gosqas/legacy` folder
* added `upgradeProvenance` HTTP endpoint that invokes `convertLegacyProvenance`
* added `convertLegacyProvenance` call in `getProvenance` if there are no prov records for a given key.
* extracted prov upload logic from `postProvenance` into `uploadProvenance` so it can also be called from `convertLegacyProvenance`
=> upgradeProvenance

packages/frontend/components/Provenance/PriorityNotices.vue, packages/frontend/pages/provenance/[deviceKey].vue, packages/frontend/test/data/provenance.ts, packages/frontend/utils/descendantList.spec.ts, packages/frontend/utils/descendantList.ts, packages/frontend/utils/types.ts
Child keys are rendering as "undefined". From real data it was observed that the child key can be undefined or [].
The root cause is the search for the child key isn't checking for both cases.
The code is moved into helper functions that can be unit tested against a real example of the provenance data structure (with fake data).
=> Child keys not rendering correctly

packages/frontend/pages/device/[deviceKey].vue, packages/frontend/pages/provenance/[deviceKey].vue
Protect against undefined childKeys. Updated device page to be the same as the provenance page - this could be broken out into a component later.
Hotfix for: https://github.com/gosqasorg/asset-provenance-tracking/pull/306
=> Fix undefined error.

packages/frontend/components/Forms/CreateContainer.vue, packages/frontend/components/Forms/CreateDevice.vue
- Added an await to the router navigation call - this is likely the cause of the bug.
- Added navigation error reporting to gather more data in case the bug is encountered again.
=> Fix page not rendering correctly after creating a new device.

packages/frontend/pages/provenance/[deviceKey].vue
Changing the body tag to div tag fixes the rendering issues where the scrollspy is hidden behind the footer. There should only be one body tag.
=> Fix scrollspy hidden behind footer

packages/frontend/components/Provenance/CreateRecord.vue
When you make a container, should the reporting keys have the "Notify all children" checkbox or not? I hid the "Notify all children" checkbox for when a user creates a device:
When you create a new container it does appear again:
However, it also appears for a container's reporting key and child keys:
=> The "Notify all Children?" checkbox is hidden when creating a new device

packages/frontend/components/TrackAsset.vue
The track asset field now accepts both URLs and record keys. I didn't change the default text on the track asset field from 'Device key' since that's what it says on the FIGMA, but I can if desired.
=> Allowed users to enter a device key or a URL to view a record

packages/frontend/components/TrackAsset.vue, packages/frontend/layouts/default.vue, packages/frontend/pages/index.vue
Moved input field to below the View Record button on mobile and fixed spacing to match FIGMA. Also changed the View Record button fill when the input field is visible.
=> Fixed View Record Mobile Bug

packages/frontend/components/Forms/CreateDevice.vue
Stopped the submission of multiple devices/containers and from sending multiple console messages to report the creation of the device. 
To this, I disabled the submission button after the device creation form is validated and submit is clicked initially.
The issue this is related to is #299
=> disabled the Create Record button when form was first submitted

packages/frontend/components/Forms/CreateContainer.vue, packages/frontend/layouts/learn_more.vue, packages/frontend/pages/history/[deviceKey].vue, packages/frontend/pages/terms_and_conditions.vue
Changed the email to the new gosqas email and converted the email on the site to links (that open an empty email to info@gosqas.org).
=> Changed Email on Website to "info@gosqas.org"

packages/frontend/pages/statistics.vue
This PR changes the titles in the statistics page:
Total Devices -> Total Records
Total Records -> Total Record Entries
Devices added -> Records added
Records added -> Record entries added
After changes:
=> Modified titles in statistics page

packages/frontend/components/csvFile.vue
This reduces the getProvenance api call to get the children keys and children names when downloading a Children CSV file.
Instead of calling the getProvenance api twice, it uses the original call to glean the children keys and children names.
=> reducing the api calls when downloading children csv file

packages/frontend/components/Forms/CreateContainer.vue
A div was missing so the "customize grouped record titles" checkbox would give an error, is now fixed and works the same as before.
=> Fixed Error on Create Container Page

packages/backend/package-lock.json, packages/backend/package.json, packages/backend/src/services/keyFuncs.spec.ts, packages/backend/src/services/keyFuncs.ts, packages/backend/test/services/keyFuncs.spec.ts
- Copy keyFuncs.ts and keyFuncs.spec.ts from frontend to backend
- Adapt for Node.js crypto API instead of Web Crypto API
- Remove async/await since Node.js randomBytes is synchronous
- Maintain same functionality and validation logic
- Tests should run with existing Vitest setup
=> Added keyFuncs service to backend
